version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data_pub:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: botwb
      POSTGRES_USER: mark
      POSTGRES_PASSWORD: ff
  api:
    container_name: my_custom_name2
    depends_on:
      - db
    image: verbinmay/wbparser-prod:latest
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "3333:3333"
    environment:
      MAINPORT: 3333
      DB_USERNAME: mark
      DB_PASSWORD: ff
      DB_NAME: botwb
      CON_DB: dev
      DB_HOST: db
      DB_PORT: '5432'

volumes:
  postgres_data_pub:
    driver: local